name: Apertium Monolingual CI/CD

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
          sudo apt-get install -qfy apertium-all-dev python3
      - name: Build
        run: |
          ./autogen.sh
          make -j2
      - name: Test
        run: |
          make test
